from enum import StrEnum

class Err(StrEnum):
    ERR_USER_FOLDER_NOT_FOUND = "User folder not found."
    ERR_GENIUS_TOKEN_NOT_FOUND = "Genius API token not found."
    ERR_STATS_FILETYPE = "The stats file must be a JSON file."
    ERR_ITUNES_MISSING_PARAMS = "Missing parameters for iTunes image fetching."
    ERR_ITUNES_INVALID_COUNTRY = "Invalid country code."
    ERR_NO_FILE = "Invalid file: No file selected."
    ERR_NO_IMG = "No image was selected or uploaded."
    ERR_IMG_INVALID_FILETYPE = "Invalid file type. Only PNG and JPG files are allowed."
    ERR_NO_IMG_URL = "No image URL provided."
    ERR_INVALID_YT_URL = "Invalid YouTube URL."
    ERR_OVERLAY_NOT_FOUND = "Overlay file not found."
    ERR_FAIL_DOWNLOAD = "Failed to download image."
    ERR_LYRICS_MISSING_PARAMS = "Missing parameters for lyrics fetching."
    ERR_LYRICS_NOT_FOUND = "Lyrics not found."
    ERR_CARDS_PARAMS_NOT_FOUND = "Missing parameters for cards generation."
    ERR_CARDS_CONTENTS_NOT_FOUND = "No cards contents were generated."
    ERR_CARDS_CONTENTS_INVALID = "Invalid provided cards contents."
    ERR_CARDS_CONTENTS_SAVE_FAILED = "Failed to save cards contents."
    ERR_CARDS_CONTENTS_READ_FAILED = "Failed to read cards contents."
    ERR_CARDS_METANAME_NOT_FOUND = "No card metaname provided."
    ERR_CARDS_CENTER_ARTWORK_NOT_FOUND = "No center artwork flipper provided."
    ERR_CARDS_BACKGROUND_NOT_FOUND = "No background image provided."
    ERR_CARDS_COLOR_NOT_FOUND = "No bottom color provided."
    ERR_CARDS_FILENAME_NOT_FOUND = "No filename provided."

class Warn(StrEnum):
    WARN_NO_USER_FOLDER = "User folder not found in session. Creating a new one."

class Msg(StrEnum):
    MSG_GENIUS_TOKEN_FETCHED = "Genius API token fetched successfully."
    MSG_STATS_FETCHED = "Statistics fetched successfully."
    MSG_STATS_CREATED = "Statistics created successfully."
    MSG_ITUNES_FETCH_COMPLETE = "iTunes image fetch complete."
    MSG_ITUNES_IMAGE_UPLOADED = "iTunes image uploaded successfully."
    MSG_LOCAL_IMAGE_UPLOADED = "Local image uploaded successfully."
    MSG_YOUTUBE_IMAGE_UPLOADED = "YouTube thumbnail uploaded successfully."
    MSG_PROCESSED_IMAGES_SUCCESS = "Processed images path retrieved successfully."
    MSG_LYRICS_FETCH_SUCCESS = "Lyrics fetched successfully."
    MSG_CARDS_CONTENTS_SAVED = "Cards contents saved successfully."
    MSG_CARDS_GENERATED = "Cards generated successfully."
    MSG_CARD_GENERATED = "Card generated successfully."