from enum import StrEnum

class Err(StrEnum):
    USER_FOLDER_NOT_FOUND = "User folder not found."
    GENIUS_TOKEN_NOT_FOUND = "Genius API token not found."
    STATS_FILETYPE = "The stats file must be a JSON file."
    ITUNES_MISSING_PARAMS = "Missing parameters for iTunes image fetching."
    ITUNES_INVALID_COUNTRY = "Invalid country code."
    NO_FILE = "Invalid file: No file selected."
    NO_IMG = "No image was selected or uploaded."
    IMG_INVALID_FILETYPE = "Invalid file type. Only PNG and JPG files are allowed."
    NO_IMG_URL = "No image URL provided."
    INVALID_YT_URL = "Invalid YouTube URL."
    OVERLAY_NOT_FOUND = "Overlay file not found."
    FAIL_DOWNLOAD = "Failed to download image."
    LYRICS_MISSING_PARAMS = "Missing parameters for lyrics fetching."
    LYRICS_NOT_FOUND = "Lyrics not found."
    CARDS_PARAMS_NOT_FOUND = "Missing parameters for cards generation."
    CARDS_CONTENTS_NOT_FOUND = "No cards contents were generated."
    CARDS_CONTENTS_INVALID = "Invalid provided cards contents."
    CARDS_CONTENTS_SAVE_FAILED = "Failed to save cards contents."
    CARDS_CONTENTS_READ_FAILED = "Failed to read cards contents."
    CARDS_METANAME_NOT_FOUND = "No card metaname provided."
    CARDS_CENTER_ARTWORK_NOT_FOUND = "No center artwork flipper provided."
    CARDS_BACKGROUND_NOT_FOUND = "No background image provided."
    CARDS_COLOR_NOT_FOUND = "No bottom color provided."
    CARDS_FILENAME_NOT_FOUND = "No filename provided."

class Warn(StrEnum):
    NO_USER_FOLDER = "User folder not found in session. Creating a new one."

class Msg(StrEnum):
    GENIUS_TOKEN_FETCHED = "Genius API token fetched successfully."
    STATS_FETCHED = "Statistics fetched successfully."
    STATS_CREATED = "Statistics created successfully."
    ITUNES_FETCH_COMPLETE = "iTunes image fetch complete."
    ITUNES_IMAGE_UPLOADED = "iTunes image uploaded successfully."
    LOCAL_IMAGE_UPLOADED = "Local image uploaded successfully."
    YOUTUBE_IMAGE_UPLOADED = "YouTube thumbnail uploaded successfully."
    PROCESSED_IMAGES_SUCCESS = "Processed images path retrieved successfully."
    LYRICS_FETCH_SUCCESS = "Lyrics fetched successfully."
    CARDS_CONTENTS_SAVED = "Cards contents saved successfully."
    CARDS_GENERATED = "Cards generated successfully."
    CARD_GENERATED = "Card generated successfully."